on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup environment
      - name: Install poetry
        run: pipx install poetry
      
      - name: Configure poetry
        run: poetry config virtualenvs.create false
        
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
      
      - name: Install dependencies
        run: poetry install --with dev

      # Ensure the code is clean
      - name: Lint code
        run: pylint my_ml

      # Run code
      - name: Simulate training
        run: python my_ml/main.py

      # Evaluate the results
      - name: Display training results
        run: cat accuracy.txt
